# Generated by Django 6.0.6 on 2026-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adddepartment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=225)),
                ('department_code', models.IntegerField()),
                ('department_head', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('department_email', models.IntegerField(max_length=100)),
                ('department_number', models.IntegerField(max_length=12)),
                ('create_at', models.TimeField()),
            ],
        ),
    ]
