# Generated by Django 6.0.6 on 2026-07-16 04:06

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adddepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='empadd',
            fields=[
                ('emp_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='profile')),
                ('address', models.CharField(verbose_name=builtins.max)),
            ],
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='department_email',
            field=models.CharField(max_length=100),
        ),
    ]
