# Generated by Django 6.0.6 on 2026-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fileupload_alter_empadd_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(default='Pending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
