# Generated by Django 6.0.6 on 2026-07-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fileupload_status_alter_fileupload_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
