# Generated by Django 6.0.6 on 2026-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_fileupload_create_at_alter_fileupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='create_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
