# Generated by Django 6.0.6 on 2026-07-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_adddepartment_create_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='login',
        ),
    ]
