# Generated by Django 6.0.6 on 2026-07-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_adminlogin_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='create_at',
        ),
    ]
