# Generated by Django 6.0.6 on 2026-07-22 04:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_login_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_history',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('File_no', models.CharField(max_length=100)),
                ('current_user', models.CharField(max_length=225)),
                ('forwarded_user', models.CharField(max_length=225)),
                ('action', models.CharField(max_length=225)),
                ('remark', models.CharField(verbose_name=builtins.max)),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
