# Generated by Django 6.0.6 on 2026-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_login_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
